### ISSUE TITLE
Doesn't work with new bga

### ISSUE THREAD

**Issue by simy69** [oliverosz/bga-export-stats#1]
It gives error.
On Opera:
![image](https://user-images.githubusercontent.com/14070748/149063551-3535e0e9-e403-4898-8ba1-8dda52a2cd54.png)
On Firefox:
![image](https://user-images.githubusercontent.com/14070748/149063824-d8f5d82d-cba4-4693-8912-1a89ac3ee440.png)
Thanks

**Comment by oliverosz** [comment]
Thanks, I will look into it.
